x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "${MYSQL_PASSWORD}"
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  panel:
    &panel-environment
    APP_URL: "http://${PANEL_DOMAIN}" # Set to http if you are not using HTTPS (localhost)
    # Source: https://github.com/EdyTheCow/docker-pterodactyl/issues/28
    APP_KEY: "${APP_KEY}"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "admin@example.com"
    # See here for more information: https://pterodactyl.io/panel/1.0/additional_configuration.html#telemetry
    PTERODACTYL_TELEMETRY_ENABLED: false
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:

  database:
    image: mariadb:10.5
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "pterodactyl_database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:v1.9.1
    restart: always
    networks:
      - pterodactyl
      - local
    links:
      - database
      - cache
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    labels:
      # HTTP
      - "traefik.http.routers.pterodactyl_panel.entrypoints=web"
      - "traefik.http.routers.pterodactyl_panel.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.services.pterodactyl_panel.loadbalancer.server.port=80"
      # HTTPS - If you don't want HTTPS (using localhost as APP_URL), comment out the following lines
      - "traefik.http.routers.pterodactyl_panel.middlewares=panel_https"
      - "traefik.http.middlewares.panel_https.redirectscheme.scheme=https"
      - "traefik.http.routers.pterodactyl_panel-https.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl_panel-https.rule=Host(`${PANEL_DOMAIN}`)"
      - "traefik.http.routers.pterodactyl_panel-https.tls=true"
      - "traefik.http.routers.pterodactyl_panel-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.pterodactyl_panel-https.loadbalancer.server.port=80"

networks:
  local:
    external: false
  pterodactyl:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  pterodactyl_database:
    external: false
