services:
  traefik:
    image: traefik:v3.0
    env_file:
      - .env
    networks:
      - pterodactyl
    restart: always
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080" # Port for the dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json

networks:
  pterodactyl:
    external: true
